version: '3.7'

services:
  gulp:
    container_name: gulp
    image: "fknorre/gulp:latest"
    tty: true
    command: ./runGulp.sh
    environment:
      FILENAME_CONCAT: 'app.js'
      FILENAME_MIN: 'app.min.js'
    volumes:
     - ./resources/javascript/:/gulp/javascript
     - ./webroot/js/:/gulp/js